export let MoveBack = {
  "/migoto-cms/createUser":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse/:id":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse/:id/createCourse":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse/:id/createModule":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse/:id/createScenario/aiScenario":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse/:id/createScenario/createAvatar":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse/:id/createScenario/createAvatar/personaCreation":"/migoto-cms/dashboard",
  "/migoto-cms/createUser/assignCourse/:id/createScenario/personaCreation": "/migoto-cms/dashboard",
  "/migoto-cms/createCourse": "/migoto-cms/dashboard",
  "/migoto-cms/createModule": "/migoto-cms/dashboard",
  "/migoto-cms/createScenario/createAvatar": "/migoto-cms/dashboard",
  "/migoto-cms/createScenario/createAvatar/personaCreation": "/migoto-cms/dashboard",
  "/migoto-cms/selectScenario": "/migoto-cms/dashboard",
  "/migoto-cms/selectScenario/personaCreation":"/migoto-cms/dashboard",
  "/migoto-cms/selectScenario/personaCreation/createAvatar": "/migoto-cms/dashboard",
  "/migoto-cms/users/createUser": "/migoto-cms/users",
  "/migoto-cms/users/:id": "/migoto-cms/users",
  "/migoto-cms/users/:id/assignCourse/:id": "/migoto-cms/users",
  "/migoto-cms/courseManagement/createCourse": "/migoto-cms/courseManagement",
  "/migoto-cms/courseManagement/createModule": "/migoto-cms/courseManagement",
  "/migoto-cms/courseManagement/createScenario": "/migoto-cms/courseManagement",
  "/migoto-cms/courseManagement/createScenario/createAvatar": "/migoto-cms/courseManagement",
  "/migoto-cms/courseManagement/createScenario/personaCreation": "/migoto-cms/courseManagement",
  "/migoto-cms/courseManagement/createCourse/createAvatar/personaCreation": "/migoto-cms/courseManagement",
};
