export let NavBar = {
  "/migoto-cms/dashboard":["Dashboard"],
  
  "/migoto-cms/createUser":["Dashboard","Create User"],
  "/migoto-cms/createUser/bulkList":["Dashboard","Create User"],
  "/migoto-cms/createUser/assignCourse":["Dashboard","Create User", "Assign Course"],
  "/migoto-cms/createUser/assignCourse/:id":["Dashboard","Create User", "Assign Course"],
  "/migoto-cms/createUser/assignCourse/:id/createCourse":["Dashboard","Create User", "Assign Course", "Create Course"],
  "/migoto-cms/createUser/assignCourse/:id/createModule":["Dashboard","Create User", "Create Course",'Create Module'],
  "/migoto-cms/createUser/assignCourse/:id/createScenario":["Dashboard","Create User", "Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createUser/assignCourse/:id/createScenario/editContent":["Dashboard","Create User", "Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createUser/assignCourse/:id/createScenario/videoPdf":["Dashboard","Create User", "Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createUser/assignCourse/:id/createScenario/avatarSelection":["Dashboard","Create User", "Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createUser/assignCourse/:id/createScenario/Assign":["Dashboard","Create User", "Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createUser/assignCourse/:id/createScenario/createAvatar":["Dashboard","Create User", "Create Course",'Create Module','Create Scenario',"Create Avatar"],
  "/migoto-cms/createUser/assignCourse/:id/createScenario/aiScenario": ["Dashboard","Create User", "Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createUser/assignCourse/:id/createCourse/personaCreation": ["Dashboard","Create User", "Create Course",'Create Module','Create Scenario',"Create Persona"],
  
  "/migoto-cms/createCourse": ["Dashboard","Create Course"],
  "/migoto-cms/createModule": ["Dashboard","Create Course",'Create Module'],
  "/migoto-cms/createScenario": ["Dashboard","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createScenario/editContent": ["Dashboard","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createScenario/videoPdf": ["Dashboard","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createScenario/avatarSelection": ["Dashboard","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createScenario/Assign": ["Dashboard","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/createScenario/createAvatar": ["Dashboard","Create Course",'Create Module','Create Scenario',"Create Avatar"],
  "/migoto-cms/createScenario/personaCreation": ["Dashboard","Create Course",'Create Module','Create Scenario',"Create Persona"],
  "/migoto-cms/createScenario/createAvatar/personaCreation": "/migoto-cms/dashboard",
  
  "/migoto-cms/selectScenario": ["Dashboard","Select Course"],
  "/migoto-cms/selectScenario/personaCreation":["Dashboard","Select Course","Create Persona"],
  "/migoto-cms/selectScenario/createAvatar": ["Dashboard","Select Course","Create Avatar"],
  
  "/migoto-cms/users/createUser": ["User Management","Create User"],
  "/migoto-cms/users/createUser/bulkList": ["User Management","Create User"],
  "/migoto-cms/users": ["User Management"],
  "/migoto-cms/users/:id": ["User Management"],
  "/migoto-cms/users/:id/course": ["User Management"],
  "/migoto-cms/users/:id/course/editUser": ["User Management","Edit User"],
  "/migoto-cms/users/:id/module/editUser": ["User Management","Edit User"],
  "/migoto-cms/users/:id/scenario/editUser": ["User Management","Edit User"],
  "/migoto-cms/users/:id/assignCourse/:id": ["User Management","Assign Course"],
  "/migoto-cms/users/:id/course/assignCourse/:id": ["User Management","Assign Course"],
  "/migoto-cms/users/:id/module/assignCourse/:id": ["User Management","Assign Course"],
  "/migoto-cms/users/:id/scenario/assignCourse/:id": ["User Management","Assign Course"],
  "/migoto-cms/users/:id/module": ["User Management"],
  "/migoto-cms/users/:id/scenario": ["User Management"],
  "/migoto-cms/users/:id/chats": ["User Management"],
  
  "/migoto-cms/courseManagement": ["Course Management"],
  "/migoto-cms/courseManagement/showModule": ["Course Management"],
  "/migoto-cms/courseManagement/showScenario": ["Course Management"],
  "/migoto-cms/courseManagement/showAvatarInteraction": ["Course Management"],
  "/migoto-cms/courseManagement/createCourse": ["Course Management","Create Course"],
  "/migoto-cms/courseManagement/createModule": ["Course Management","Create Course",'Create Module'],
  "/migoto-cms/courseManagement/showModule/createModule": ["Course Management",'Create Module'],
  "/migoto-cms/courseManagement/createScenario": ["Course Management","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showModule/createScenario": ["Course Management",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showScenario/createScenario": ["Course Management",'Create Scenario'],
  "/migoto-cms/courseManagement/createScenario/editContent": ["Course Management","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showModule/createScenario/editContent": ["Course Management",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showScenario/createScenario/editContent": ["Course Management",'Create Scenario'],
  "/migoto-cms/courseManagement/createScenario/videoPdf": ["Course Management","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showModule/createScenario/videoPdf": ["Course Management",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showScenario/createScenario/videoPdf": ["Course Management",'Create Scenario'],
  "/migoto-cms/courseManagement/createScenario/personaCreation": ["Course Management","Create Course",'Create Module','Create Scenario', "Create Persona"],
  "/migoto-cms/courseManagement/showModule/createScenario/personaCreation": ["Course Management",'Create Module','Create Scenario', "Create Persona"],
  "/migoto-cms/courseManagement/showScenario/createScenario/personaCreation": ["Course Management",'Create Scenario', "Create Persona"],
  "/migoto-cms/courseManagement/createScenario/createAvatar": ["Course Management","Create Course",'Create Module','Create Scenario', "Create Avatar"],
  "/migoto-cms/courseManagement/showModule/createScenario/createAvatar": ["Course Management",'Create Module','Create Scenario', "Create Avatar"],
  "/migoto-cms/courseManagement/showScenario/createScenario/createAvatar": ["Course Management",'Create Scenario', "Create Avatar"],
  "/migoto-cms/courseManagement/createScenario/avatarSelection": ["Course Management","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showModule/createScenario/avatarSelection": ["Course Management",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showScenario/createScenario/avatarSelection": ["Course Management",'Create Scenario'],
  "/migoto-cms/courseManagement/createScenario/Assign": ["Course Management","Create Course",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showModule/createScenario/Assign": ["Course Management",'Create Module','Create Scenario'],
  "/migoto-cms/courseManagement/showScenario/createScenario/Assign": ["Course Management",'Create Scenario'],
  
  "/migoto-cms/admins": ["Admin Management"],
  "/migoto-cms/admins/createAdmin": ["Admin Management","Create Admin"],
  "/migoto-cms/admins/:id/editAdmin": ["Admin Management","Edit Admin"],
};
