
  export let TimeLineRoute = {
      "/migoto-cms/createUser": [
          {
            id: 1,
            number: "01",
            status: "warning",
            heading: "User Creation",
            description: "In Progress",
          },
          {
            id: 2,
            number: "02",
            status: "error",
            heading: "Assign Course",
            description: "",
          },
        ],
      "/migoto-cms/createUser/assignCourse/:id":[
          {
            id: 1,
            number: "01",
            status: "warning",
            heading: "User Creation",
            description: "In Progress",
          },
          {
            id: "Course Selection",
            number: "01",
            status: "warning",
            heading: "Course Selection",
            title: "Completion level",
            description: "In Progress",
          },
          {
            id: "Module Selection",
            number: "02",
            status: "error",
            heading: "Module Selection",
            title: "",
            description: "",
          },
          {
            id: "Scenario Selection",
            number: "03",
            status: "error",
            heading: "Scenario Selection",
            title: "",
            description: "",
          },
          {
            id: "Assign Course",
            number: "04",
            status: "error",
            heading: "Assign Course",
            title: "",
            description: "",
          },
      
        ],
    "/migoto-cms/createUser/assignCourse/:id/createCourse":[
        {
          id: 0,
          number: "01",
          status: "warning",
          heading: "User Creation",
          description: "In Progress",
        },
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 7,
          number: "06",
          status: "error",
          heading: "Assign Course",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createUser/assignCourse/:id/createModule":[
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "User Creation",
          description: "In Progress",
        },
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createUser/assignCourse/:id/createScenario":[
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "User Creation",
          description: "In Progress",
        },
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createUser/assignCourse/:id/createScenario/createAvatar":[
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "User Creation",
          description: "In Progress",
        },
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createUser/assignCourse/:id/createScenario/personaCreation":[
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "User Creation",
          description: "In Progress",
        },
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createCourse": [
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Create Course",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Docs & Videos",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 7,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createModule": [
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createScenario": [
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createScenario/createAvatar": [
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/createScenario/personaCreation": [
        {
          id: 1,
          number: "01",
          status: "warning",
          heading: "Course Creation",
          title: "Completion level",
          description: "In Progress",
        },
        {
          id: 2,
          number: "02",
          status: "error",
          heading: "Create Module",
          title: "",
          description: "",
        },
        {
          id: 3,
          number: "03",
          status: "error",
          heading: "Create Scenario",
          title: "",
          description: "",
        },
        {
          id: 4,
          number: "04",
          status: "error",
          heading: "Upload Document & Video",
          title: "",
          description: "",
        },
        {
          id: 5,
          number: "05",
          status: "error",
          heading: "Create Persona",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Create Avatar",
          title: "",  
          description: "",
        },
        {
          id: 6,
          number: "06",
          status: "error",
          heading: "Select User",
          title: "",
          description: "",
        },
      ],
    "/migoto-cms/selectScenario": [
      {
      id: "Course Selection",
      number: "01",
      status: "warning",
      heading: "Course Selection",
      title: "Completion level",
      description: "In Progress",
    },
    {
      id: "Module Selection",
      number: "02",
      status: "error",
      heading: "Module Selection",
      title: "",
      description: "",
    },
    {
      id: "Scenario Selection",
      number: "03",
      status: "error",
      heading: "Scenario Selection",
      title: "",
      description: "",
    },
    {
      id: 5,
      number: "05",
      status: "error",
      heading: "Create Persona",
      title: "",  
      description: "",
    },
    {
      id: 6,
      number: "06",
      status: "error",
      heading: "Create Avatar",
      title: "",  
      description: "",
    },
      ],
    "/migoto-cms/selectScenario/personaCreation":["Dashboard","Select Course","Create Persona"],
    "/migoto-cms/selectScenario/createAvatar": ["Dashboard","Select Course","Create Avatar"],
    "/migoto-cms/users/createUser": [
      {
        id: 1,
        number: "01",
        status: "warning",
        heading: "User Creation",
        description: "In Progress",
      },
      {
        id: 2,
        number: "02",
        status: "error",
        heading: "Assign Course",
        description: "",
      },
    ],
    "/migoto-cms/users": ["User Management"],
    "/migoto-cms/users/:id": ["User Management"],
    "/migoto-cms/users/:id/assignCourse/:id": ["User Management","Assign Course"],
    "/migoto-cms/courseManagement": ["Course Management"],
    "/migoto-cms/courseManagement/createCourse": ["Course Management","Create Course"],
    "/migoto-cms/courseManagement/createScenario/createAvatar": ["Course Management","Create Course", "Create Avatar"],
    "/migoto-cms/courseManagement/createScenario/personaCreation": ["Course Management","Create Course", "Create Persona"],
  };
